" Javascript
setlocal suffixesadd+=.js,.ts,.tsx,.jsx
" Indenting
setlocal smarttab
setlocal expandtab
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
" Wildignore
setlocal wildignore+=*/node_modules/*
setlocal wildignore+=*/dist/*
setlocal wildignore+=*/build/*
